async-pool:
  url: https://github.com/socketry/async-pool.git
  command: bundle exec sus
async-websocket:
  url: https://github.com/socketry/async-websocket.git
  command: bundle exec sus
async-dns:
  url: https://github.com/socketry/async-dns.git
  command: bundle exec sus
async-http:
  url: https://github.com/socketry/async-http.git
  command: bundle exec sus
falcon:
  url: https://github.com/socketry/falcon.git
  command: bundle exec sus
async-rest:
  url: https://github.com/socketry/async-rest.git
  command: bundle exec sus
